gitlab_address: https://gitlab.com

gitlab_api_starting_page: 1
gitlab_api_ending_page: 99

repo_paths:
  - xjbrh8wxe87eqqzgavme
  - ckbb9zgjjnqwzeyvered

branch_names:
  - origin/main
  - origin/develop

ip_regexes:
  - '[^0-9]10\.\d{1,3}\.\d{1,3}\.\d{1,3}'
  - '172\.\d{1,3}\.\d{1,3}\.\d{1,3}'
  - '192\.\d{1,3}\.\d{1,3}\.\d{1,3}'

file_extensions:
  - .svg
  - .jpg
  - .bmp
  - .png
  - .csv
  - .exe
  - .dll
  - .lib

paths_to_exclude:
  - test_folder/test_file
